name: Reddit Digest

on:
  schedule:
    # Run daily at 16:00 UTC (18:00 CEST)
    - cron: '0 16 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-digest:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Verify Environment Variables
      run: |
        echo "Checking EMAIL_SENDER: ${EMAIL_SENDER:0:1}***@${EMAIL_SENDER#*@}"
        echo "Checking EMAIL_RECIPIENT: ${EMAIL_RECIPIENT:0:1}***@${EMAIL_RECIPIENT#*@}"
        echo "Checking REDDIT_CLIENT_ID exists: ${REDDIT_CLIENT_ID:0:4}..."
        echo "Checking REDDIT_CLIENT_SECRET exists: ${REDDIT_CLIENT_SECRET:0:4}..."
        echo "Checking EMAIL_PASSWORD exists: ${#EMAIL_PASSWORD} characters"
      env:
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        
    - name: Run Reddit digest script
      run: python src/reddit_email.py --run-once
      env:
        REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
        REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        REDDIT_USER_AGENT: 'script:reddit-digest:v1.0'
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: 'smtp.gmail.com'
        SMTP_PORT: '587'

